In [12]:
from stable_baselines.bench.monitor import load_results
import pandas as pd

# Import monitoring data from all training
data_frames = []
for n in range(1, 3):
    train_df = load_results("training_logs/test_" + str(n))
    train_df["run"] = df.apply(lambda _: n, axis=1)
    data_frames.append(train_df)

df = pd.concat(data_frames)
df['timestep'] = df.apply(lambda row: row['index']*row['l'], axis=1)
df

      index         r   l           t  run  timestep
0         0 -0.364815  32    3.411126    1       0.0
1         0 -0.446436  32    3.411135    1       0.0
2         0 -0.168830  32    3.411163    1       0.0
3         0 -0.807119  32    3.411244    1       0.0
4         0 -0.311803  32    3.411283    1       0.0
...     ...       ...  ..         ...  ...       ...
7803    243 -0.024202  32  365.354315    2    7776.0
7804    243 -0.016504  32  365.354436    2    7776.0
7805    243 -0.007689  32  365.354531    2    7776.0
7806    243 -0.012924  32  365.354733    2    7776.0
7807    243 -0.037324  32  365.354810    2    7776.0

[15616 rows x 6 columns]

In [19]:
df = df.groupby(['run', 'index']).mean()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Plot with standard error
sns.set()
plt.figure(figsize=(10,5))
plt.title("Average evolution of episode reward on 10 OneLegBulletEnv training, PPO2")
sns.lineplot(x="timestep", y="r", data=df)